- name: restart postgresql
  service: name=postgresql state=restarted
  become: yes

- name: restart gunicorn
  service: name=gunicorn state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted
  become: yes